import { FormEvent, useEffect, useState } from 'react'
import { ArrowLeft, Check, Database, Image, LayoutDashboard, LogOut, Settings, Trophy } from 'lucide-react'
import { Link } from 'react-router-dom'
import { isSupabaseConfigured, supabase } from '../services/supabase'
import { site as fallbackSite } from '../data/content'

type SettingsForm = typeof fallbackSite & { primary_color: string; secondary_color: string; highlight_color: string }
const initial: SettingsForm = { ...fallbackSite, primary_color: '#315C75', secondary_color: '#78956D', highlight_color: '#E8C65A' }

export default function AdminPage() {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [user,setUser]=useState<string|null>(null)
  const [form,setForm]=useState(initial); const [status,setStatus]=useState(''); const [tab,setTab]=useState('settings')
  useEffect(()=>{ if(!supabase)return; supabase.auth.getUser().then(({data})=>setUser(data.user?.email||null)); supabase.from('site_settings').select('value').eq('key','site').maybeSingle().then(({data})=>{if(data?.value)setForm({...initial,...data.value})}) },[])
  const login=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;const {data,error}=await supabase.auth.signInWithPassword({email,password});setStatus(error?.message||'Signed in.');setUser(data.user?.email||null)}
  const save=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;setStatus('Saving…');const {error}=await supabase.from('site_settings').upsert({key:'site',value:form});setStatus(error?.message||'Changes saved.');}
  const logout=async()=>{await supabase?.auth.signOut();setUser(null)}

  if(!isSupabaseConfigured) return <div className="admin-setup"><Link to="/"><ArrowLeft/> Back to website</Link><div className="setup-card"><Database size={42}/><p className="kicker">Admin setup</p><h1>Connect Supabase to activate your dashboard.</h1><p>The public portfolio is already using its built-in content. Add your Supabase URL and anonymous key to the deployment environment to enable secure sign-in, editing, and image uploads.</p><code>VITE_SUPABASE_URL<br/>VITE_SUPABASE_ANON_KEY<br/>VITE_ADMIN_EMAIL</code></div></div>

  if(!user) return <div className="login-page"><Link to="/"><ArrowLeft/> Back to website</Link><form onSubmit={login}><p className="kicker">Private dashboard</p><h1>Welcome back, Mia.</h1><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button>Sign in</button>{status&&<p>{status}</p>}</form></div>

  return <div className="admin-shell"><aside><Link to="/" className="brand"><span>SW</span> Portfolio</Link><nav><button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}><Settings/>Site settings</button><button onClick={()=>setTab('projects')}><LayoutDashboard/>Projects</button><button onClick={()=>setTab('gallery')}><Image/>Gallery</button><button onClick={()=>setTab('awards')}><Trophy/>Awards</button></nav><button className="logout" onClick={logout}><LogOut/>Sign out</button></aside><main className="admin-main"><div className="admin-title"><div><p className="kicker">Portfolio manager</p><h1>{tab==='settings'?'Site settings':tab[0].toUpperCase()+tab.slice(1)}</h1></div><span>{user}</span></div>{tab==='settings'?<form className="settings-form" onSubmit={save}><div className="form-card"><h2>Identity</h2><label>Public name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Nickname<input value={form.nickname} onChange={e=>setForm({...form,nickname:e.target.value})}/></label><label>Homepage headline<textarea value={form.headline} onChange={e=>setForm({...form,headline:e.target.value})}/></label><label>Introduction<textarea value={form.intro} onChange={e=>setForm({...form,intro:e.target.value})}/></label></div><div className="form-card"><h2>Links</h2><label>Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>GitHub<input value={form.github} onChange={e=>setForm({...form,github:e.target.value})}/></label><label>LinkedIn<input value={form.linkedin} onChange={e=>setForm({...form,linkedin:e.target.value})}/></label></div><div className="form-card color-form"><h2>Colors</h2><label>Blue<input type="color" value={form.primary_color} onChange={e=>setForm({...form,primary_color:e.target.value})}/></label><label>Green<input type="color" value={form.secondary_color} onChange={e=>setForm({...form,secondary_color:e.target.value})}/></label><label>Yellow<input type="color" value={form.highlight_color} onChange={e=>setForm({...form,highlight_color:e.target.value})}/></label></div><button className="save-button"><Check/>Save changes</button>{status&&<p className="save-status">{status}</p>}</form>:<CollectionPlaceholder type={tab}/>}</main></div>
}

function CollectionPlaceholder({type}:{type:string}){return <div className="collection-card"><h2>{type[0].toUpperCase()+type.slice(1)} manager</h2><p>This collection is ready for the Supabase content table. Once the project is connected, entries can be added, reordered, published, or hidden here without changing the website layout.</p><button disabled>Add new entry</button></div>}
