import { ChangeEvent, FormEvent, useEffect, useState } from 'react'
import { ArrowLeft, Check, Database, Image, LayoutDashboard, LogOut, Plus, Settings, Trash2, Trophy, Upload } from 'lucide-react'
import { Link } from 'react-router-dom'
import { isSupabaseConfigured, supabase } from '../services/supabase'
import { site as fallbackSite } from '../data/content'
import '../admin.css'

type SettingsForm = typeof fallbackSite & { primary_color:string; secondary_color:string; highlight_color:string }
const initial:SettingsForm={...fallbackSite,primary_color:'#315C75',secondary_color:'#78956D',highlight_color:'#E8C65A'}
type Tab='settings'|'projects'|'gallery'|'awards'
type Row={id:string;title:string;published:boolean;summary?:string;data?:Record<string,unknown>}

export default function AdminPage(){
  const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [user,setUser]=useState<string|null>(null)
  const [form,setForm]=useState(initial);const [status,setStatus]=useState('');const [tab,setTab]=useState<Tab>('settings')
  useEffect(()=>{if(!supabase)return;supabase.auth.getUser().then(({data})=>setUser(data.user?.email||null));supabase.from('site_settings').select('value').eq('key','site').maybeSingle().then(({data})=>{if(data?.value)setForm({...initial,...data.value})})},[])
  const login=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;const{data,error}=await supabase.auth.signInWithPassword({email,password});setStatus(error?.message||'Signed in.');setUser(data.user?.email||null)}
  const save=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;setStatus('Saving…');const{error}=await supabase.from('site_settings').upsert({key:'site',value:form});setStatus(error?.message||'Changes saved. Refresh the public site to see them.')}
  if(!isSupabaseConfigured)return <div className="admin-setup"><Link to="/"><ArrowLeft/>Back to website</Link><div className="setup-card"><Database size={42}/><p className="kicker">Admin setup</p><h1>Connect Supabase to activate your dashboard.</h1><p>The portfolio works now with its built-in content. Add the three deployment variables to enable secure sign-in, editing, and image uploads.</p><code>VITE_SUPABASE_URL<br/>VITE_SUPABASE_ANON_KEY<br/>VITE_ADMIN_EMAIL</code></div></div>
  if(!user)return <div className="login-page"><Link to="/"><ArrowLeft/>Back to website</Link><form onSubmit={login}><p className="kicker">Private dashboard</p><h1>Welcome back, Mia.</h1><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button>Sign in</button>{status&&<p>{status}</p>}</form></div>
  return <div className="admin-shell"><aside><Link to="/" className="brand"><span>SW</span>Portfolio</Link><nav>{([['settings',Settings],['projects',LayoutDashboard],['gallery',Image],['awards',Trophy]] as const).map(([name,Icon])=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><Icon/>{name==='settings'?'Site settings':name[0].toUpperCase()+name.slice(1)}</button>)}</nav><button className="logout" onClick={async()=>{await supabase?.auth.signOut();setUser(null)}}><LogOut/>Sign out</button></aside><main className="admin-main"><div className="admin-title"><div><p className="kicker">Portfolio manager</p><h1>{tab==='settings'?'Site settings':tab[0].toUpperCase()+tab.slice(1)}</h1></div><span>{user}</span></div>{tab==='settings'?<form className="settings-form" onSubmit={save}><FormCard title="Identity"><label>Public name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Nickname<input value={form.nickname} onChange={e=>setForm({...form,nickname:e.target.value})}/></label><label>Homepage headline<textarea value={form.headline} onChange={e=>setForm({...form,headline:e.target.value})}/></label><label>Introduction<textarea value={form.intro} onChange={e=>setForm({...form,intro:e.target.value})}/></label></FormCard><FormCard title="Links"><label>Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>GitHub<input value={form.github} onChange={e=>setForm({...form,github:e.target.value})}/></label><label>LinkedIn<input value={form.linkedin} onChange={e=>setForm({...form,linkedin:e.target.value})}/></label></FormCard><div className="form-card color-form"><h2>Colors</h2>{(['primary_color','secondary_color','highlight_color'] as const).map((key,i)=><label key={key}>{['Blue','Green','Yellow'][i]}<input type="color" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><button className="save-button"><Check/>Save changes</button>{status&&<p className="save-status">{status}</p>}</form>:<CollectionManager type={tab}/>}</main></div>
}

function FormCard({title,children}:{title:string;children:React.ReactNode}){return <div className="form-card"><h2>{title}</h2>{children}</div>}

function CollectionManager({type}:{type:Exclude<Tab,'settings'>}){
  const [rows,setRows]=useState<Row[]>([]);const[editing,setEditing]=useState(false);const[message,setMessage]=useState('')
  const[draft,setDraft]=useState({title:'',subtitle:'',description:'',image:'',date:''})
  const load=async()=>{if(!supabase)return;if(type==='projects'){const{data}=await supabase.from('projects').select('id,title,summary,published').order('sort_order');setRows(data||[])}else{const{data}=await supabase.from('content_items').select('id,title,data,published').eq('collection',type==='awards'?'award':'gallery').order('sort_order');setRows(data||[])}}
  useEffect(()=>{load()},[type])
  const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file||!supabase)return;setMessage('Uploading…');const path=`${type}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9.-]/g,'-')}`;const{error}=await supabase.storage.from('portfolio-media').upload(path,file);if(error)return setMessage(error.message);const{data}=supabase.storage.from('portfolio-media').getPublicUrl(path);setDraft({...draft,image:data.publicUrl});setMessage('Image uploaded.')}
  const create=async(e:FormEvent)=>{e.preventDefault();if(!supabase)return;setMessage('Saving…');let error;if(type==='projects'){const slug=draft.title.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');({error}=await supabase.from('projects').insert({slug,title:draft.title,eyebrow:draft.subtitle,summary:draft.description,cover_url:draft.image,content:{description:[draft.description],year:draft.date||String(new Date().getFullYear()),role:'Project Lead',tags:[],hierarchy:['Domain','Task','Application','Method','Implementation'],gallery:draft.image?[draft.image]:[],featured:false},published:true}))}else{const collection=type==='awards'?'award':'gallery';const data=type==='awards'?{issuer:draft.subtitle,date:draft.date,description:draft.description,image:draft.image}:{src:draft.image,alt:draft.title,category:draft.subtitle||'Projects',caption:draft.description,orientation:'landscape'};({error}=await supabase.from('content_items').insert({collection,title:draft.title,data,published:true}))}if(error)return setMessage(error.message);setDraft({title:'',subtitle:'',description:'',image:'',date:''});setEditing(false);setMessage('Entry published.');load()}
  const remove=async(row:Row)=>{if(!supabase||!confirm(`Delete “${row.title}”?`))return;await supabase.from(type==='projects'?'projects':'content_items').delete().eq('id',row.id);load()}
  const toggle=async(row:Row)=>{if(!supabase)return;await supabase.from(type==='projects'?'projects':'content_items').update({published:!row.published}).eq('id',row.id);load()}
  return <div className="manager"><div className="manager-actions"><p>{rows.length} entries</p><button onClick={()=>setEditing(!editing)}><Plus/>Add entry</button></div>{editing&&<form className="entry-form" onSubmit={create}><label>Title<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>{type==='gallery'?'Category':'Subtitle / issuer'}<input value={draft.subtitle} onChange={e=>setDraft({...draft,subtitle:e.target.value})}/></label><label>Description<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Date / year<input value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label><label className="upload-label"><Upload/>Upload image<input type="file" accept="image/*" onChange={upload}/></label>{draft.image&&<img className="upload-preview" src={draft.image} alt="Upload preview"/>}<button className="save-button"><Check/>Publish entry</button></form>}<div className="admin-rows">{rows.map(row=><article key={row.id}><div><h3>{row.title}</h3><p>{row.summary||String(row.data?.description||row.data?.caption||'')}</p></div><button className={row.published?'published':'hidden'} onClick={()=>toggle(row)}>{row.published?'Published':'Hidden'}</button><button aria-label={`Delete ${row.title}`} onClick={()=>remove(row)}><Trash2/></button></article>)}</div>{message&&<p className="save-status">{message}</p>}</div>
}
